In [166]:
import numpy as np

**Problem - 1: Array Creation:**

---



a) Initialize an empty array with size **2x2**

In [167]:
array = np.zeros((2,2))
print(array)

[[0. 0.]
 [0. 0.]]


b) Initialize an all one array with size **4X2**

In [168]:
array = np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


c) Return a new array of given shape and type, filled with fill_value

In [169]:
array = np.full((4,2),7.14)
print(array)
#np.full(shape(rows and columns), fill_value(what to fill the array with), dtype=float)

[[7.14 7.14]
 [7.14 7.14]
 [7.14 7.14]
 [7.14 7.14]]


d) Return a new array of zeros with same shape and type as a given array

In [170]:
array = np.array([[1,2,3],
                  [4,5,6]])
z = np.zeros_like(array)
print(z)

[[0 0 0]
 [0 0 0]]


e) Return a new array of ones with same shape and type as a given array

In [171]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
o = np.ones_like(array)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


f) For an existing list new_list = [1,2,3,4] convert to an numpy array

In [172]:
new_list = [1,2,3,4]
array = np.array(new_list)
print(array)

[1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

---



a) Create an array with values ranging from 10 to 49

In [173]:
array = np.arange(10,50)
#(start value, end value(always excluded so if we take 49 it would be till 48))
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


b) Create a 3X3 matrix with values ranging from 0 to 8

In [174]:
array = np.arange(0,9)#ranges from 0 to 8
matrix = array.reshape(3,3)#coverts 1D array into 3x3 matrix
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


c) Create a 3X3 identity matrix

In [175]:
array = np.eye(3,3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


d) Create a random array of size 30 and find the mean of the array

In [176]:
array = np.random.random(30) #random values form 0 to 1 ranging the size of 30

mean_value = array.mean()
print("Array:",array)
print("Mean Value:",mean_value)#adds all and divides by 30 basically avg value nikalne


Array: [0.1212897  0.98558576 0.72110971 0.80708787 0.53164051 0.90492048
 0.9954105  0.97999385 0.34718899 0.3262979  0.47889213 0.12996945
 0.58467072 0.60405466 0.44688343 0.99601435 0.19299468 0.32882256
 0.66944798 0.95541905 0.6829671  0.74242821 0.15267671 0.90572477
 0.01370107 0.64828236 0.52105537 0.34997099 0.94073629 0.09840327]
Mean Value: 0.5721213475827033


e) Create a 10X10 array with random values and find the minimum and maximum values

In [177]:
# Create a 10x10 array with random values between 0 and 1
array = np.random.rand(10, 10)

# Find the minimum value
min_value = np.min(array)

# Find the maximum value
max_value = np.max(array)

# Print the array, minimum, and maximum
print("10x10 Random Array:\n", array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

10x10 Random Array:
 [[0.33794276 0.773159   0.27202005 0.41288494 0.92333529 0.89242704
  0.36098438 0.09923675 0.85321903 0.42309024]
 [0.75512222 0.44730782 0.71629295 0.1453669  0.61740613 0.17168236
  0.70027353 0.6728025  0.67504308 0.53335046]
 [0.2743261  0.71491069 0.61231362 0.94835635 0.70427762 0.21752531
  0.18250437 0.08269937 0.01128254 0.33824086]
 [0.95530137 0.6610247  0.47909674 0.63133234 0.68281085 0.13834706
  0.07371816 0.65007555 0.73717913 0.72003745]
 [0.26182305 0.64663427 0.62408663 0.14238945 0.00487579 0.25244796
  0.78187664 0.57751538 0.80241238 0.35389852]
 [0.6273977  0.3503616  0.20612589 0.55884721 0.00872383 0.47339716
  0.97409529 0.24822169 0.23795644 0.34967433]
 [0.44010298 0.56831482 0.61976751 0.78943566 0.46866157 0.81194285
  0.71487041 0.14784252 0.99470655 0.92722438]
 [0.93314315 0.30214741 0.24047765 0.1836145  0.53938207 0.96652323
  0.60123506 0.05288537 0.43004579 0.88790165]
 [0.96276854 0.31114965 0.62247911 0.7757613  0.22866097 0.

f) Create a zero array of size 10 and replace 5th element with 1

In [178]:
# Create a zero array of size 10
array = np.zeros(10)

# Replace the 5th element (index 4) with 1
array[4] = 1

# Print the array
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


g) Reverse an array arr = [1,2,0,0,4,0]

In [179]:
# Original array
arr = [1, 2, 0, 0, 4, 0]

# Reverse the array
reversed_arr = arr[::-1]

# Print the reversed array
print(reversed_arr)

[0, 4, 0, 0, 2, 1]


h) Create a 2d array with 1 on border and 0 inside

In [180]:
rows, cols = 5, 5 # size of the array

array = np.zeros((rows, cols), dtype=int) #array of 0s

array[0, :] = 1 # Top row
array[-1, :] = 1 # Bottom row
array[:, 0] = 1 # Left column
array[:, -1] = 1 # Right column

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


i) Create a 8X8 matrix and fill it with a checkerboard pattern

In [181]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1 # 1s in alternate positions on odd rows
checkerboard[::2, 1::2] = 1 # 1s in alternate positions on even rows

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

---



For the following arrays:



In [182]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

Complete all the task using numpy:

---



a) Add the two array

In [183]:
sum_xy = x + y # 2D array addition
sum_vw = v + w # 1D array addition

print("x + y =\n", sum_xy)
print("v + w =", sum_vw)


x + y =
 [[ 6  8]
 [10 13]]
v + w = [20 22]


b) Subtract the two arrays

In [184]:
diff_xy = x - y # 2D array subtraction
diff_vw = v - w # 1D array subtraction

print("x - y =\n", diff_xy)
print("v - w =", diff_vw)

x - y =
 [[-4 -4]
 [-4 -3]]
v - w = [-2 -2]


c) Multiply the array with any integers of your choice

In [185]:
# Multiply arrays with integers
mul_x = x * 2 # Multiply 2D array x by 2
mul_y = y * 2 # Multiply 2D array y by 2
mul_v = v * 3 # Multiply 1D array v by 3
mul_w = w * 3 # Multiply 1D array w by 3

print("x * 2 =\n", mul_x)
print("y * 2 =\n", mul_y)
print("v * 3 =", mul_v)
print("w * 3 =", mul_w)

x * 2 =
 [[ 2  4]
 [ 6 10]]
y * 2 =
 [[10 12]
 [14 16]]
v * 3 = [27 30]
w * 3 = [33 36]


d) Find the square of each element of the array

In [186]:
# Square each element
square_x = x ** 2
square_y = y ** 2
square_v = v ** 2
square_w = w ** 2

print("x squared =\n", square_x)
print("y squared =\n", square_y)
print("v squared =", square_v)
print("w squared =", square_w)

x squared =
 [[ 1  4]
 [ 9 25]]
y squared =
 [[25 36]
 [49 64]]
v squared = [ 81 100]
w squared = [121 144]


e) Find the dot product between: v(and)w ; x(and)v ; x(and)y

In [187]:
vw_dot = np.dot(v, w)
xv_dot = np.dot(x, v)
xy_dot = np.dot(x, y)

print("v · w =", vw_dot)
print("x · v =\n", xv_dot)
print("x · y =\n", xy_dot)

v · w = 219
x · v =
 [29 77]
x · y =
 [[19 22]
 [50 58]]


f) Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions

In [188]:
xy_row = np.vstack((x, y))
print("Concatenate x and y along row =\n", xy_row)

Concatenate x and y along row =
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


g) Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [189]:
x = np.array([[1,2],[3,5]])
v = np.array([9,10])

np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

A Value error occured because numpy cannot concatenate a 2D array with a 1D array directly ; they must have the same number of dimensions.

**Problem - 4: Matrix Operations:**

---



For the following arrays:

In [190]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Prove following with Numpy:

---



a) Prove A.A^-1 = I

In [191]:
A_inv = np.linalg.inv(A)
print("Inverse of A =\n", A_inv)

I = np.dot(A, A_inv)
print("A · A_inv =\n", I)

I_expected = np.eye(2)
print("Expected Identity matrix =\n", I_expected)

print("Is A·A_inv equal to I? ", np.allclose(I, I_expected))



Inverse of A =
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A · A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Expected Identity matrix =
 [[1. 0.]
 [0. 1.]]
Is A·A_inv equal to I?  True


b) Prove AB ̸= BA.

In [192]:
AB = np.dot(A, B)
print("AB =\n", AB)

BA = np.dot(B, A)
print("BA =\n", BA)

print("Is AB equal to BA? ", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Is AB equal to BA?  False


c) Prove (AB)^T = B^TA^T

In [193]:
AB = np.dot(A, B)
AB_T = AB.T
print("(AB)^T =\n", AB_T)

B_T = B.T
A_T = A.T

BTA_T = np.dot(B_T, A_T)
print("B^T · A^T =\n", BTA_T)

print("Is (AB)^T equal to B^T·A^T? ", np.array_equal(AB_T, BTA_T))


(AB)^T =
 [[23 51]
 [13 29]]
B^T · A^T =
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T·A^T?  True


d) Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [194]:
# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant matrix
B = np.array([-1, -3, 9])

# Find inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)
print("Solution [x, y, z] =", X)



Solution [x, y, z] = [ 2.  1. -2.]


**4.2 Experiment: How Fast is Numpy?**

---



a) Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [195]:
import time

N = 1000000  # size

# Python lists
list1 = list(range(N))
list2 = list(range(N))

start = time.time()
sum_list = [list1[i] + list2[i] for i in range(N)]
end = time.time()
print("Time with Python lists:", end - start, "seconds")

# NumPy arrays
arr1 = np.arange(N)
arr2 = np.arange(N)

start = time.time()
sum_array = arr1 + arr2
end = time.time()
print("Time with NumPy arrays:", end - start, "seconds")

Time with Python lists: 0.13008666038513184 seconds
Time with NumPy arrays: 0.002178192138671875 seconds


b) Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [196]:
import time

N = 1000000  # size of lists/arrays

# Python lists
list1 = list(range(N))
list2 = list(range(N))

start = time.time()
mul_list = [list1[i] * list2[i] for i in range(N)]
end = time.time()
print("Time with Python lists:", end - start, "seconds")

# NumPy arrays
arr1 = np.arange(N)
arr2 = np.arange(N)

start = time.time()
mul_array = arr1 * arr2
end = time.time()
print("Time with NumPy arrays:", end - start, "seconds")

Time with Python lists: 0.20879912376403809 seconds
Time with NumPy arrays: 0.0029888153076171875 seconds


c) Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [197]:
import time

N = 1000000  # size of lists/arrays

# Python lists
list1 = list(range(N))
list2 = list(range(N))

start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(N))
end = time.time()
print("Time with Python lists:", end - start, "seconds")
print("Dot product (Python lists) =", dot_list)

# NumPy arrays
arr1 = np.arange(N)
arr2 = np.arange(N)

start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print("Time with NumPy arrays:", end - start, "seconds")
print("Dot product (NumPy arrays) =", dot_array)

Time with Python lists: 0.10329103469848633 seconds
Dot product (Python lists) = 333332833333500000
Time with NumPy arrays: 0.001870870590209961 seconds
Dot product (NumPy arrays) = 333332833333500000


d) Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [198]:
import time
import random

N = 1000  # size of matrices

# Python lists
matrix1 = [[random.randint(0, 10) for _ in range(N)] for _ in range(N)]
matrix2 = [[random.randint(0, 10) for _ in range(N)] for _ in range(N)]

# Matrix multiplication
start = time.time()
result_list = [[0]*N for _ in range(N)]
for i in range(N):
    for j in range(N):
        for k in range(N):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]
end = time.time()
print("Time with Python lists:", end - start, "seconds")

# NumPy arrays
arr1 = np.random.randint(0, 11, size=(N, N))
arr2 = np.random.randint(0, 11, size=(N, N))

# Matrix multiplication
start = time.time()
result_array = np.dot(arr1, arr2)
end = time.time()
print("Time with NumPy arrays:", end - start, "seconds")

Time with Python lists: 293.04671454429626 seconds
Time with NumPy arrays: 1.9863190650939941 seconds
